CITY: "brno"
DISPLAY_NAME: "Brno"
JSON_PREFIX: "CITY_BRNO"
CAPTION_TEMPLATE: "Akce v Brně {date}\n\n#brno #party #akcebrno #kamvbrne"
LOCATION: "Brno, Czech Republic"
SCRAPERS:
    - title: "Bobyhall"
      url: "https://bobyhall.cz/program-bobyhall/"
      baseUrl: "https://bobyhall.cz/"
      parser: "bobyhall"
    - title: "Fraktal"
      url: "https://ra.co/clubs/224489/events"
      baseUrl: "https://ra.co/"
      parser: "ra"
    - title: "pul.pit"
      url: "https://ra.co/clubs/206733/events"
      baseUrl: "https://ra.co/"
      parser: "ra"
    - title: "Metro Music Bar"
      url: "https://www.metromusic.cz/program/"
      baseUrl: "https://www.metromusic.cz/"
      parser: "metro"
    - title: "První patro"
      url: "https://patrobrno.cz/"
      baseUrl: "https://patrobrno.cz/"
      parser: "patro"
    - title: "Perpetuum"
      url: "https://www.perpetuumklub.cz/program/"
      baseUrl: "https://www.perpetuumklub.cz/"
      parser: "perpetuum"
    - title: "Fléda"
      url: "https://www.fleda.cz/program/"
      baseUrl: "https://www.fleda.cz/"
      parser: "fleda"
    - title: "Sono Music Club"
      url: "https://www.sono.cz/program/"
      baseUrl: "https://www.sono.cz/"
      parser: "sono"
    - title: "Kabinet Múz"
      url: "https://www.kabinetmuz.cz/program"
      baseUrl: "https://www.kabinetmuz.cz/"
      parser: "kabinet"
    - title: "Artbar"
      url: "https://www.artbar.club/shows"
      baseUrl: "https://www.artbar.club/"
      parser: "artbar"
